### ISSUE TITLE
Upcoming major Manticore release

### ISSUE THREAD

**Issue by githubmanticore** [nck-2/test-rep#148]
## Pre-release: 
 
- [ ] Review changes in the docs comparing them with the previous version's docs 
- [ ] In the release notes don't forget about breaking changes 
- [ ] Update our feature list in the introduction 
- [ ] TMP: Make sure we announce/document: 
  - [ ] https://gitlab.com/manticore_support/layout/-/issues/12#note_1328405268 (REPLACE changes both) 
  - [ ] https://gitlab.com/effyis/effyis/-/issues/321 - master/agent version change 
- [ ] update package info: titles / descriptions / licenses 
- [ ] TMP: Update in docs `/Installation/Windows#Using-the-installer` (link to the installer) 
- [ ] Ask Ivinco to do pre-release testing 
- [ ] Wait until they finish at least partly (e.g. it works fine on sehs01), but before we release officially it's best if the upgrade fully in production 
- [ ] TMP: Add info about `FATAL: binlog meta file /var/lib/manticore/binlog.meta is v.12, binary is v.13; recovery requires previous binary version` to the changelog 
- [ ] Decide on the commit that will be released - ??? (later: `RELEASE COMMIT`) 
- [ ] Decide on the next version name and discuss with the team - 6.0.0 / 2.0.0 
- [ ] Make sure the build passes Valgrind testing (ask Alexey to run it) 
- [ ] Make sure the build passes the manual memleak check (https://gitlab.com/manticoresearch/dev/-/issues/3299#note_1279706600) 
- [ ] Make sure UK lemmatizer is supported in all OS (including new ones) 
   
## Release candidate 
 
- MCL: 
  - [ ] Make release `x.y.z` 
  - [ ] update version in `columnar VERSION x.x.x` in CMakeLists.txt to `x.x.x` 
  - [ ] make draft MR to trigger CI 
  - [ ] make sure the CI has generated the packages in `release_candidate` directories 
  - [ ] close the MR 
- Lemmatizer: 
  - [ ] Update version in `CMakeLists.txt` to `x.y.z` 
  - [ ] make sure the CI has generated the packages in `release_candidate` directories 
- Buddy: 
  - [ ] Make release branch `x.y.z` 
  - [ ] Make tag `x.y.z` to trigger CI 
  - [ ] make sure the CI has generated the packages in `release_candidate` directories 
- Backup: 
  - [ ] Make release branch `x.y.z` 
  - [ ] Make tag `x.y.z` to trigger CI 
  - [ ] make sure the CI has generated the packages in `release_candidate` directories 
- Executor: 
  - [ ] Make release branch `x.y.z` 
  - [ ] Make tag `x.y.z` to trigger CI 
  - [ ] make sure the CI has generated the packages in `release_candidate` directories 
- Daemon: 
  - [ ] Make release branch `manticore-x.y.z` 
  - [ ] Update daemon's version in `VERNUMBERS "x.x.x"` in `src/sphinxversion.h.in` to `x.x.x` 
  - [ ] Update `./manual/latest_release_version` and make sure the `docs_deploy` CI job is triggered to run. Note, it's triggered for commits to `manticore-x.y.z`, but not for merge request pipelines. 
  - [ ] update `deps.txt` in the daemon to the commit. Related [issue](https://raw.githubusercontent.com/manticoresoftware/issue_attachments/main/download/1690399293_3208). 
  - [ ] Update daemon's version in `manual/latest_release_version` to `x.x.x` 
  - [ ] Make sure to run the CI with `PACK_ICUDATA=1`, otherwise `icudata` package won't be made 
  - [ ] make draft MR to trigger CI 
  - [ ] make sure the CI has generated the packages in `release_candidate` directories 
  - [ ] close the MR 
- Homebrew 
  - [ ] Update formulas in the branch `release_candidate` 
  - [ ] Build more bottles 
    ``` 
    `for n in manticore-backup manticore-buddy manticore-executor manticore-columnar-lib; do echo  
    "==================== $n ================="; brew install manticoresoftware/rc/$n --build-bottle; done` 
 
    `for n in manticore-backup manticore-buddy manticore-executor manticore-columnar-lib; do echo  
    "==================== $n ================="; brew bottle manticoresoftware/rc/$n; done` 
 
    update the formulas in the branch `release_candidate` 
 
    `for f in manticore-backup manticore-buddy manticore-executor manticore-columnar-lib; do echo $f; brew style $f.rb; done` 
 
    update the dependencies in manticore-extra.rb and manticoresearch.rb to /rc/ 
 
    commit the changes to the branch release_candidate and push 
 
    rename the bottles, so they look similar to the ones on github 
    upload the bottles to https://github.com/manticoresoftware/homebrew-manticore/releases 
 
    sync https://github.com/manticoresoftware/homebrew-rc/tree/release_candidate 
 
    `brew install manticoresoftware/rc/manticore-extra --build-bottle` 
    `brew install manticoresoftware/rc/manticoresearch --build-bottle` 
 
    `for n in manticore-extra manticoresearch; do echo "==================== $n ================="; brew bottle manticoresoftware/rc/$n; done` 
 
    rename the bottles, so they look similar to the ones on github 
    upload the bottles to https://github.com/manticoresoftware/homebrew-manticore/releases 
 
    for f in manticore-extra manticoresearch; do echo $f; brew style $f.rb; done 
    add the new bottles to the formulas 
    update the dependencies in extra.rb and manticoresearch.rb from /rc/ back to /manticore/ 
    commit and push 
 
    sync https://github.com/manticoresoftware/homebrew-rc/tree/release_candidate 
 
    brew ls|grep manticore|xargs brew uninstall; brew untap manticoresoftware/rc; brew untap manticoresoftware/manticore 
 
    Make sure everything is installable from bottles: 
 
    brew install --force-bottle manticoresoftware/rc/manticore-backup 
    brew install --force-bottle manticoresoftware/rc/manticore-buddy 
    brew install --force-bottle manticoresoftware/rc/manticore-executor 
    brew install --force-bottle manticoresoftware/rc/manticore-columnar-lib 
    brew install --force-bottle manticoresoftware/rc/manticore-extra 
    brew install --force-bottle manticoresoftware/rc/manticoresearch 
 
    The last 2 won't succeed. Now merge all from the branch "release_candidate" to the "main" branch and try: 
    brew install --force-bottle manticoresoftware/manticore/manticoresearch manticoresoftware/manticore/manticore-extra 
 
    If it works - all is ok 
    ``` 
  - [ ] Test `brew install manticoresoftware/manticore/manticoresearch manticoresoftware/manticore/manticore-extra` 
 
## Testing RC 
- [ ] NICK Test manticoresearch-php with the new version. The instruction is [here](https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/testing.md) 
- [ ] NICK Test one of the generated clients 
- [ ] Make sure `yum install manticore` works properly for all Centos versions we support 
- [ ] Make sure `apt install manticore` works properly for all Ubuntu/Debian versions we support 
- [ ] Test lemmatizer-uk 
- [ ] Centos 7, 8, 9: 
  ``` 
  sudo yum -y install https://repo.manticoresearch.com/manticore-repo.noarch.rpm; sudo yum -y --enablerepo manticore-release-candidate install manticore manticore-extra 
  systemctl start manticore 
  mysql -P9306 -h0 -e "show status like '%version%'; show queries;" 
  ``` 
- [ ] all ubuntus and debians: 
  ``` 
  wget https://repo.manticoresearch.com/manticore-release-candidate-repo.noarch.deb && sudo dpkg -i manticore-release-candidate-repo.noarch.deb && sudo apt -y update && sudo apt -y install manticore manticore-extra 
  systemctl start manticore 
  mysql -P9306 -h0 -e "show status like '%version%'; show queries;" 
  ``` 
- [ ] update links on https://manticoresearch.com/install 
- [ ] test installation in all the OS 
 
## Release: 
- [ ] Wait until Ivinco finishes the testing 
- [ ] Update version in [readme.md](https://raw.githubusercontent.com/manticoresoftware/issue_attachments/main/download/1690399295_README.md) in the release branch and cherry-pick it to the master branch 
- Push release branches to GitHub: 
  - [ ] Columnar 
  - [ ] Daemon 
- [ ] move `release_candidate` dirs to just `release` 
- [ ] regenerate Windows installer, so it links with proper packages 
- [ ] replace `release_candidate` with `release` (deb OS) or just emptiness (rhel OS) in the manual / on the site 
- [ ] publish the site 
- [ ] publish the manual: update manual.manticoresearch.com by updating env var `DOC_VERSION` for deployment 'latest' in Rancher 
- [ ] move `release` dirs to `release_old` and `release_candidate` to `release` 
- [ ] Make sure release tags exist on GitHub for: 
  - [ ] Columnar 
  - [ ] Daemon 
  - [ ] Docker 
- [ ] make sure https://manual.manticoresearch.com/ points to the release 
- [ ] Update release docker 
    ``` 
    docker buildx build --progress plain --push --platform linux/arm64,linux/amd64 --tag  manticoresearch/manticore:6.0.0 . 
    docker buildx build --progress plain --push --platform linux/arm64,linux/amd64 --tag  manticoresearch/manticore:latest . 
    ``` 
  - [ ] update readme on docker hub (link to the latest release) 
- [ ] Release homebrew formulae 
- [ ] Make sure all the download links on /install/ are correct  
- [ ] Make sure `yum install manticore` works properly for all Centos versions we support 
- [ ] Make sure `apt install manticore` works properly for all Ubuntu/Debian versions we support 
- [ ] Make "release" on GitHub 
- [ ] Bump versions to after-release in all the components 
- [ ] Release next version of Manticore Executor Kit, see https://github.com/manticoresoftware/phar_builder/blob/main/Dockerfile#L78 
 
## Post-release: 
- [ ] Copy our formulae to the official homebrew repo 
- [ ] Backup/Buddy/Executor releases on GitHub 
- [ ] After publishing edit `src/sphinxversion.h.in` and bump the version. Commit and push the changes. 
- [ ] Bump version in columnar in `CMakeLists.txt`. Commit and push. 
- [ ] Release new helm chart version KLIM - https://gitlab.com/manticoresearch/manticoresearch-helm/-/issues/36 
- [ ] Prepare tasks for new courses on play.manticoresearch.com SERGEY 
- [ ] Update base images on play.manticoresearch.com and make sure all the courses are working NICK 
- [ ] Update link here https://github.com/manticoresoftware/manticoresearch-backup#how-to-use 
- [ ] Update https://manticoresearch.com/about/  
- [ ] Update https://manual.manticoresearch.com/Installation/Windows#Installing-Manticore-in-Windows 
- [ ] Backup repo (create snapshot on https://robot.your-server.de/storage) 
- [ ] Make sure everything from the new branch has been also commited to the master branch (e.g. from `./manual`) 
- [ ] Replace label "rel::upcoming" with "rel::X.Y.Z" 
- [ ] Replace label "rel::next" with "rel::upcoming" 
- [ ] Update cheatsheet if required 
- [ ] Make a PR to Homebrew core repo with a full copy of our custom tap 
- [ ] TMP Create a task for Dmitrii to change the scheme of Manticore Backup packages deployment to repo. , so each commit to the main branch makes it to repo.manticoresearch.com 
- [ ] TMP Test well in Windows (there were a couple of complaints about 5.0.2) 
 
## PR: 
- [ ] Update https://github.com/manticoresoftware/manticoresearch/releases 
- [ ] Update https://github.com/manticoresoftware/docker/releases 
- [ ] Update https://github.com/manticoresoftware/columnar/releases 
- [ ] Inform our clients (when possible, emphasize things each client can benefit from) 
- [ ] Release blogpost is ready - SERGEY 
- [ ] Short announcement text is ready - GLORIA 
- [ ] Short annoncemet text is approved - SERGEY 
- [ ] Announcement in telegram - GLORIA 
- [ ] Twitter post is made - GLORIA 
- [ ] Vk.com post is made - GLORIA 
- [ ] Post in linkedin is made - GLORIA 
- [ ] Announcement on forum is made - GLORIA 
- [ ] Announcement on Facebook is made - GLORIA 
- [ ] Announcement in public slack is made (use `@channel`) - GLORIA 
- [ ] Newsletter is sent - SERGEY 
- [ ] TMP Make blogpost from http://localhost:8080/Searching/Cost_based_optimizer#Cost-based-optimizer 
- [ ] TMP Make blogpost about Buddy
